### ISSUE TITLE
Missing Resources

### ISSUE THREAD

**Issue by Gusher** [Ainlid/first_person_exploration_template#1]
Getting missing resources errors when trying to open..
<img width="219" alt="Capture" src="https://user-images.githubusercontent.com/261646/112102116-03676e80-8b65-11eb-8516-542dd80f1029.PNG">

**Comment by Ainlid** [comment]
I just tested both Asset Library and Github pages and couldn't get this message. which way did you download the template? do you see the listed files in the resource tab?

**Comment by Gusher** [comment]
I installed in my project folder, but will try again.... will try to fix dependencies and see what happens... will try again.. I got it from godot website and added manually..

**Comment by Ainlid** [comment]
by doing it manually do you mean just adding the files or importing the .godot project file?

**Comment by Ainlid** [comment]
I tried the former and even that works besides the fader which has to be added to autoload this way

**Comment by Gusher** [comment]
.... All good, just realized it's best to import, not install manually.... very nice demo, loved it! I hope to see an update on it....
